#!/usr/bin/env python
# SPDX-FileCopyrightText: 2024 Google LLC
# SPDX-License-Identifier: Apache-2.0


from __future__ import with_statement
from string import Template
import re
import fnmatch
import os

VERSION = "0.10.0"

TEST_FUNC_REGEX = r"^(void\s+(%s__(\w+))\(\s*void\s*\))\s*\{"

EVENT_CB_REGEX = re.compile(r"^(void\s+clar_on_(\w+)\(\s*void\s*\))\s*\{", re.MULTILINE)

# Deliberately more permissive than TEST_FUNC_REGEX: it tolerates leading
# whitespace, a storage-class qualifier, an empty argument list and any suite
# stem, so that it matches the test-shaped functions the strict regex silently
# skips. The separators are `\s`, like TEST_FUNC_REGEX, so that a definition
# split across lines is still seen; a tolerant pattern that is stricter than the
# strict one leaves a blind spot exactly where the guard is needed.
TEST_FUNC_TOLERANT_REGEX = re.compile(
    r"^([ \t]*)((?:(?:static|inline|extern)\s+)*)"
    r"void\s+((\w+)__(\w+))\s*\(\s*(void)?\s*\)\s*\{",
    re.MULTILINE,
)

# Preprocessor blocks that the compiler never sees. The guard must not report a
# function that no build compiles; comments are already removed before it runs,
# but `#if 0` is not a comment.
DISABLED_BLOCK_START_REGEX = re.compile(r"^[ \t]*#[ \t]*if[ \t]+(?:0|FALSE)[ \t]*$")

COND_START_REGEX = re.compile(r"^[ \t]*#[ \t]*if")

COND_BRANCH_REGEX = re.compile(r"^[ \t]*#[ \t]*(?:else|elif)")

COND_END_REGEX = re.compile(r"^[ \t]*#[ \t]*endif")

# Naming conventions that mark a test as intentionally not registered:
# a leading underscore, or a DISABLED_ / DISABLED__ prefix.
INTENTIONALLY_DISABLED_REGEX = re.compile(r"^(_+|DISABLED_+)")

SKIP_COMMENTS_REGEX = re.compile(
    r'//.*?$|/\*.*?\*/|\'(?:\\.|[^\\\'])*\'|"(?:\\.|[^\\"])*"', re.DOTALL | re.MULTILINE
)

CATEGORY_REGEX = re.compile(r"CL_IN_CATEGORY\(\s*\"([^\"]+)\"\s*\)")

CLAR_HEADER = (
    """
/*
 * Clar v%s
 *
 * This is an autogenerated file. Do not modify.
 * To add new unit tests or suites, regenerate the whole
 * file with `./clar`
 */
"""
    % VERSION
)

CLAR_EVENTS = ["init", "shutdown", "test", "suite"]


def main():
    from optparse import OptionParser

    parser = OptionParser()

    parser.add_option("-c", "--clar-path", dest="clar_path")
    parser.add_option("-v", "--report-to", dest="print_mode", default="default")
    parser.add_option("-f", "--file", dest="file")

    options, args = parser.parse_args()

    folder = args[0] or "."
    print("folder: %s" % folder)
    builder = ClarTestBuilder(
        folder, clar_path=options.clar_path, print_mode=options.print_mode
    )

    if options.file is not None:
        builder.load_file(options.file)
    else:
        builder.load_dir(folder)

    builder.render()


class ClarTestBuilder:
    def __init__(self, path, clar_path=None, print_mode="default"):
        self.declarations = []
        self.suite_names = []
        self.callback_data = {}
        self.suite_data = {}
        self.category_data = {}
        self.event_callbacks = []
        self.current_file = None
        self.registered_symbols = set()

        self.clar_path = os.path.abspath(clar_path) if clar_path else None

        self.path = os.path.abspath(path)
        self.modules = [
            "clar_sandbox.c",
            "clar_fixtures.c",
            "clar_fs.c",
            "clar_mock.c",
            "clar_categorize.c",
        ]

        self.modules.append("clar_print_%s.c" % print_mode)

    def load_dir(self, folder):
        print("Loading test suites...")

        for root, dirs, files in os.walk(self.path):
            module_root = root[len(self.path) :]
            module_root = [c for c in module_root.split(os.sep) if c]

            tests_in_module = fnmatch.filter(files, "*.c")

            for test_file in tests_in_module:
                full_path = os.path.join(root, test_file)
                test_name = "_".join(module_root + [test_file[:-2]])

                with open(full_path) as f:
                    self.current_file = full_path
                    self._process_test_file(test_name, f.read())

    def load_file(self, filename):
        with open(filename, encoding="latin-1") as f:
            test_name = os.path.basename(filename)[:-2]
            self.current_file = filename
            self._process_test_file(test_name, f.read())

    def render(self):
        if not self.suite_data:
            raise RuntimeError('No tests found under "%s"' % self.path)

        if not os.path.isdir(self.path):
            os.makedirs(self.path)

        main_file = os.path.join(self.path, "clar_main.c")
        with open(main_file, "w") as out:
            out.write(self._render_main())

        header_file = os.path.join(self.path, "clar.h")
        with open(header_file, "w") as out:
            out.write(self._render_header())

        print('Written Clar suite to "%s"' % self.path)

    #####################################################
    # Internal methods
    #####################################################

    def _render_cb(self, cb):
        return '{"%s", &%s}' % (cb["short_name"], cb["symbol"])

    def _render_suite(self, suite, index):
        template = Template(
            r"""
    {
        ${suite_index},
        "${clean_name}",
        ${initialize},
        ${cleanup},
        ${categories},
        ${cb_ptr}, ${cb_count}
    }
"""
        )

        callbacks = {}
        for cb in ["initialize", "cleanup"]:
            callbacks[cb] = self._render_cb(suite[cb]) if suite[cb] else "{NULL, NULL}"

        if len(self.category_data[suite["name"]]) > 0:
            cats = "_clar_cat_%s" % suite["name"]
        else:
            cats = "NULL"

        return template.substitute(
            suite_index=index,
            clean_name=suite["name"].replace("_", "::"),
            initialize=callbacks["initialize"],
            cleanup=callbacks["cleanup"],
            categories=cats,
            cb_ptr="_clar_cb_%s" % suite["name"],
            cb_count=suite["cb_count"],
        ).strip()

    def _render_callbacks(self, suite_name, callbacks):
        template = Template(
            r"""
static const struct clar_func _clar_cb_${suite_name}[] = {
    ${callbacks}
};
"""
        )
        callbacks = [
            self._render_cb(cb)
            for cb in callbacks
            if cb["short_name"] not in ("initialize", "cleanup")
        ]

        return template.substitute(
            suite_name=suite_name, callbacks=",\n\t".join(callbacks)
        ).strip()

    def _render_categories(self, suite_name, categories):
        template = Template(
            r"""
static const char *_clar_cat_${suite_name}[] = { "${categories}", NULL };
"""
        )
        if len(categories) > 0:
            return template.substitute(
                suite_name=suite_name, categories='","'.join(categories)
            ).strip()
        else:
            return ""

    def _render_event_overrides(self):
        overrides = []
        for event in CLAR_EVENTS:
            if event in self.event_callbacks:
                continue

            overrides.append("#define clar_on_%s() /* nop */" % event)

        return "\n".join(overrides)

    def _render_header(self):
        template = Template(self._load_file("clar.h"))

        declarations = "\n".join(
            "extern %s;" % decl for decl in sorted(self.declarations)
        )

        return template.substitute(
            extern_declarations=declarations,
        )

    def _render_main(self):
        template = Template(self._load_file("clar.c"))
        suite_names = sorted(self.suite_names)

        suite_data = [
            self._render_suite(self.suite_data[s], i) for i, s in enumerate(suite_names)
        ]

        callbacks = [
            self._render_callbacks(s, self.callback_data[s]) for s in suite_names
        ]

        callback_count = sum(len(cbs) for cbs in self.callback_data.values())

        categories = [
            self._render_categories(s, self.category_data[s]) for s in suite_names
        ]

        return template.substitute(
            clar_modules=self._get_modules(),
            clar_callbacks="\n".join(callbacks),
            clar_categories="".join(categories),
            clar_suites=",\n\t".join(suite_data),
            clar_suite_count=len(suite_data),
            clar_callback_count=callback_count,
            clar_event_overrides=self._render_event_overrides(),
        )

    def _load_file(self, filename):
        if self.clar_path:
            filename = os.path.join(self.clar_path, filename)
            with open(filename) as cfile:
                return cfile.read()

        else:
            import zlib
            import base64
            import sys

            content = CLAR_FILES[filename]

            if sys.version_info >= (3, 0):
                content = bytearray(content, "utf_8")
                content = base64.b64decode(content)
                content = zlib.decompress(content)
                return str(content, "utf-8")
            else:
                content = base64.b64decode(content)
                return zlib.decompress(content)

    def _get_modules(self):
        return "\n".join(self._load_file(f) for f in self.modules)

    def _skip_disabled_blocks(self, text):
        """Blank out `#if 0` / `#if FALSE` regions, keeping the line count."""
        lines = []
        depth = 0

        for line in text.split("\n"):
            if depth:
                if COND_START_REGEX.match(line):
                    depth += 1
                elif COND_END_REGEX.match(line):
                    depth -= 1
                elif depth == 1 and COND_BRANCH_REGEX.match(line):
                    depth = 0
                lines.append("")
                continue

            if DISABLED_BLOCK_START_REGEX.match(line):
                depth = 1
                lines.append("")
                continue

            lines.append(line)

        return "\n".join(lines)

    def _skip_comments(self, text):
        def _replacer(match):
            s = match.group(0)
            return "" if s.startswith("/") else s

        return re.sub(SKIP_COMMENTS_REGEX, _replacer, text)

    def _process_test_file(self, suite_name, contents):
        contents = self._skip_comments(contents)

        self._process_events(contents)
        self._process_declarations(suite_name, contents)
        self._check_registration(suite_name, contents)
        self._process_categories(suite_name, contents)

    def _check_registration(self, suite_name, contents):
        """Fail the build on a test-shaped function that did not register.

        A function that looks like a clar test but does not match
        TEST_FUNC_REGEX is skipped without a word, so a typo in a name silently
        deletes a test. Compare what the file defines against what actually
        reached callback_data and report the difference.
        """
        problems = []
        contents = self._skip_disabled_blocks(contents)

        for (
            ws,
            qualifier,
            symbol,
            stem,
            _short,
            void_arg,
        ) in TEST_FUNC_TOLERANT_REGEX.findall(contents):
            if INTENTIONALLY_DISABLED_REGEX.match(symbol):
                continue

            if not symbol.startswith("test_"):
                continue

            if symbol in self.registered_symbols:
                continue

            reasons = []
            if ws:
                reasons.append("the line does not start at column 0")
            if qualifier:
                reasons.append(
                    "the return type is prefixed with `%s`" % qualifier.strip()
                )
            if not void_arg:
                reasons.append("the argument list is `()` and must be `(void)`")
            if stem != suite_name:
                reasons.append(
                    "the suite stem is `%s` and must be `%s` to match the source "
                    "file name" % (stem, suite_name)
                )
            if not reasons:
                reasons.append("it does not match %r" % (TEST_FUNC_REGEX % suite_name))

            problems.append("  %s: %s" % (symbol, "; ".join(reasons)))

        if problems:
            raise RuntimeError(
                "%s: test-shaped functions were not registered by clar and would "
                "never run:\n%s\nRename them so they match "
                "`void %s__<name>(void)` at column 0, or mark them intentionally "
                "disabled with a leading underscore or a DISABLED_ prefix."
                % (self.current_file or suite_name, "\n".join(problems), suite_name)
            )

    def _process_events(self, contents):
        for decl, event in EVENT_CB_REGEX.findall(contents):
            if event not in CLAR_EVENTS:
                continue

            self.declarations.append(decl)
            self.event_callbacks.append(event)

    def _process_declarations(self, suite_name, contents):
        callbacks = []
        initialize = cleanup = None
        self.registered_symbols = set()

        regex_string = TEST_FUNC_REGEX % suite_name
        regex = re.compile(regex_string, re.MULTILINE)

        for declaration, symbol, short_name in regex.findall(contents):
            self.registered_symbols.add(symbol)
            data = {
                "short_name": short_name,
                "declaration": declaration,
                "symbol": symbol,
            }

            if short_name == "initialize":
                initialize = data
            elif short_name == "cleanup":
                cleanup = data
            else:
                callbacks.append(data)

        if not callbacks:
            return

        tests_in_suite = len(callbacks)

        suite = {
            "name": suite_name,
            "initialize": initialize,
            "cleanup": cleanup,
            "cb_count": tests_in_suite,
        }

        if initialize:
            self.declarations.append(initialize["declaration"])

        if cleanup:
            self.declarations.append(cleanup["declaration"])

        self.declarations += [callback["declaration"] for callback in callbacks]

        callbacks.sort(key=lambda x: x["short_name"])
        self.callback_data[suite_name] = callbacks
        self.suite_data[suite_name] = suite
        self.suite_names.append(suite_name)

        print("  %s (%d tests)" % (suite_name, tests_in_suite))

    def _process_categories(self, suite_name, contents):
        self.category_data[suite_name] = [
            cat for cat in CATEGORY_REGEX.findall(contents)
        ]


CLAR_FILES = {
    "clar.c": r"""eJy1G2tz2zbyu34FrJxjyqZkS+ldrn51cm6a813qtLUz7Uzi4VAkKNGhCIWP2G5P//128QZJyUnq5kMsAdjF7mLfgPZ3yeVP3/82/CHN6Blb3hfpbF5d0bvqkEwOJt+QV4zNMkpevz4ju/u9fbn6dRrRvKTD85jmVZqktDgkL5ZhNKfDyegAV/aepHmU1TElx2FZ0qIazU+tsZJWN4tlY6yKs3TaGktZc6hI81nXWOkOLsJq3sIWFg3QOk9hGMeQu4J+rNOCxiRhBSnDPJ6yO8CMHFlo7sv96n5JG/vhcFmFnFMYTmKakODX84tnk94TolfdpnnMbgWoGZVMmoFyTrMsXKaN4RiIi+QOBDZIc0qCH1+cXwRnZyQIophGmTWF5HhLkIMPHwckcL+bdYsPgFhOLFhMYakZstZFcz1IAuuLWRFGES1LF1V7zKawiOulB384efoLMpEmOZdh8OP5xatfn02CAAYJWRbhbBGSiC0WoH0e6IxP+lxezyb9AV9ikOfR8t6rmE+Sgi18UrGgTH8HouRUUPJJOaxWBVe/vL04e3H10sH2a/Dmv+RgYg9dBueX35//4t0NiOfdkackgJEfYGRAtk7IgUtMvgQlrQL60ZvWiV/+7ieLyg/9KTIu5hIgR85pEvQqwEWzknajVB8TXJXHadIjBFUU5Qes1lElDp9cXr24Cq6Oek84Li5kXPP24vzq6uXlVfD9y3+9feUoYjrLw0yoocDszILO34YpaiQB88GPyzT2JgNuMaTDylpqa+lCBzstNhpcSIrURv0oC4vRvA9DEunZa7DBq3+fX3g5KF+K/4X8uPIBOT0hHgwNyNOnBL8f43eYBe2bMpYRRBbQuyWYHDiBYCk8GTkhSQjSO7IWyamARVFdoP/Qa8DNBXCm7jI5eNTrITtpRD6xFHxOGRQLL2J5WYGlhQXZDUpWFxEdHDXXReCqu1b6xB6MKVi52cSe6iXpXVUXNECrdDBNw7KBRi3NwwUV6PhJCOkUBXjKP+CcbIgKNj6CMThCgp+DvF5MaXHUWFbWaUWbgwlEIgWbwQmugeUbB4tyxicUu1GRLquU5UAlIW06d3OIbEe9lZGJXNNkIIQT/0QDxUfHlKRdEsq/iU1KzTirwkyP2dKIWJ1XeqigSwY6IRYGLM/uFQZ6l4JK5WJqHUtm047JLCwrC5yrj7ebsQgoizIa5vVy4PHR3cGRWuDOg4bcZyyMOQKlzVURLpYMj0dzq0cCmofTjALACoIEENNQmaTOo5bAUbeODIVLCAGcroE6LQPPZc0R4L4QTuld84wUtta2aZ5WaZiBr++cliw30e1GYUVnrEhpaaZawFzrxUEA/sA9a2QCHOQPEF+kK+CubncUoae0rduaRWo9V2t8S93kQMuiuKGWDadhoS3ndQU5SP4waq6E3ND4wHqUfBHHB9bqd0jIVtb1aFiO5HhNV8IZ8pveRAwkIfiLeBNKzpHXLSWbZ65JmxCFU7BTBxG4H5+MRqNB83Rl6rjmdOtczisVlyuQFhtcTbu4Fyz6sAYxTgUFhey6gbmxROp5N36l7L9TZxdNnJy/D9IykH5PGLzXPnZhq7tdhGg0AtqRq5r7DLggzDJPGFyX3n0OAVKFHSYEHcsCkog7KaGXnyiKAPabhtEHwj6BMqcQc1BGf/tDaDkuCfTMisO9qCs2ozktYL+YKzCJwyok03tOhwWucCOgHlKeZ9WI420uA/O5fHcNKQj6SIlHjK6c0Ce8lAUlrBwAbSAxuDrqBFMUNyHdcen8zlhBBf/oLzFMlw0t7nFgJyAKHe1pdw97jNcEO/7HV0Ee1ojxE0HryATK2zn4DOKJaUjUL96+fj3g0iIEgQGEzw1PBSocbzu7vT2fKH+GK5KCUk/CWalIa1YOKOLUFiuk2KZUE26COBG0QjjpdYitznnC4j0QovwN8yY+blqlMgd9KiJGlJUm2c2HelJ8TBLIJSAWttMGccAKZH1iTR5Mz4G2hHii1eA1txuQE6zQ5KnjQsP78BTyD60YfAEhjWlkgs+IQsXrv8+fDB/pX1+qiIWa/FLnOXYiUICHZLuEqPM+7/v8O+ipSM0RSAxICh216pT1gchDgX+pbHbu58qgY0EXkEoYBxqznOgQqz0jJSpp1WnJ3h4f5s2ZBbhWEub3hG84hKNVGMiCVnMWc4fSSak2nc5ZRbNe5ciknaEPjE9wvRWXOa+tG05DpjZSmcyp+XKkybYa99oGRU61wSnlHKx3CXb60xEZ+R9hyZucBgiGrxyeNrPcVAtr64H0QGwlSC4olJR5Q85OvYNFuRSKVUh1Qm99xjG52aDkRaSA8ovK/4yzEmtttbSLPyMSVW50HJUyMOwnein/CjHs2BamLBHI3l6q3JGzmRQ//nmXXo/UZkr9lNd/Khf45KlmSDtzPaZct3ReXyF7I310Live6iQHaJ8VBfdShEWa3ZM4LYWH6QzwqJbgzLIuvXwoULX1dp3Yv+TQ2rJWK3pNQXPSPlPIK92iagmhLsOZm/WGxUwwpPz+W1yCzp68YzyXKK/f59zr49Ija+UbMX0Ik844IcPyt9/eV+8riB8ETYJUcypEQEQZReC4kVMC69rQ6THOnb6vzmWHTZk3ERNcVGUH4EdCcNs3uKUwTLEU9g8rMgdXG+bCjXUA/yyAfwYySViSkrEc/4Yye4SSr2vLTED9VOiaztfkgshymXzz6rgDvDKCCkkJWUWaRAICMnUEUjBoKt5wvMbnLsOihKqkmJW8HoYPka/6CPDlk5XLup5hLDwDAjjOQCtHjf1uWIhYwNAtE1aT7w6uMb7uDHeUrVqqxsEOrpXpl7dpFc0t2PG13jEsKdkpdw7JH2jXM7CM3NEZnwjPCaSLEkmEXZEm8R4AWiDMJwnG6BNrl8k1Jl47JzsD8h15Rg7J5MiCzGAjDgnBQ2AZ+6As2PDMmJy6kQxI0WnB7J3I/Y6MtFCQ6rPiDv/BPphXqK8oQyPhU6DvYAd9oBk7hrFvtVR5ocDJ8/DPLhlDJrln4xgiioHZAVMCa39iGDw4skcdQlBQh86mxBHG2ICueuqv/NDWFyBQyket4bETRGF26FQXiwOeJ3PKbWniqKzBB8jU6Um7qhw43Hf0VfqXtlPajknMoLbOGW+DlpXIdnFjW17GFJuCsLy2CONPnfIYEBnWVk0Wt4yU//c/Lcp3w/G1OhOLG66FNyK034ABo9kPWvyjJt4MGkfNb6GgOFE7+G4NfyOivY/qKusVRxc2cnizhr/HIvxhut0S60uJFv+mBQ0/2EOrBk8mg3HDvFvVr9O5Cyb92iIEZ4j11c52uQOSqfN4pCKt8B6WLTeUTpFi0SrNcH+fiHACQQGiRI3tHh5RMBKPyNU8LSHDgah6i9EtjiFfApWr2BIsleBFDCd6ZDnlCp2y5TC/yMM2OqrCNUjnqX2DXLox7wJI99wOrrVT2ZTR8Y9lRy3xEKBVvWnNVe2g9Rl1urfXdFNbUnMNNSqn9okWzMDVWUnAUwfG1smGkrZ8MW4skHy2VupMJeYa+QW66NSTm1Nfs64reW5h6UiOLR6+Kj/uMhxL2z/uHDqEtCs8OwpKNBb8zw14t8jZCJr+GUNTLhIwobL1wyyzjk8bW9Onr+1vt5yy63CdGL0Rm9emofsQjCAySxCy5L9RMCp7vkLNELQQrwaoYanKA0ZAMchNzZ0eHegKBf81A9BDsUcn69vPYiyLuFHwqHWzJgJpr2RaaWe6oy5JTY+VkDi58imBS+mfPplNNw59yBb7XaRe6XJFklo9olRtH/Rlzv7Gcn5f54ntukudox0SlE/uyOtWLSlZouPe8GDgaHFMk7DOqkP7ILoy3JXqZ5j7LlHQcae2oZRrXthybFYu5d6F+M1pW3f4XL/f4w29nmqeWheCAxCvzqi6QscP/DoUFUSC8Hqfe27QmJwWI6MqduxY6T6HdYc4cFr3nDlDF0qDnJKx3WMzpa+QFRdSo8m3KU0zLUWjW0avOhU5dSrddXllet3gsnETznF0t2A3HVW7R6aPTvcQ1RbWsHMHa42be2FOreizdWzCGw/yKls8mXNut/FEe6YhEYh7EeSR3+GyPE6xW2Taa+bhjd8zD2+a8/rFTXPCuuxS8OWc1VkccKUUVrLuvs7ouaKr0eJ9op4ByqeUnQ/WeKr9L4xgsD2Y/LSezWiBNl+EaUm9y/NX5xdXA/1iTHXlzDUcWimLvLHPlZAlXovgQVOTVbrUviPRiZTLYus6r+t6Rc+K20cHScd9oJmUQDJLa2VuR+4S+YhCr7Qfq+iFyv+3LddahHqDl27y3ZYctZ5uwaR6KSQntSopBsRDLikmS59cCbUvVzGnFRbg3rj2uhJb0fFpm5O8YeJJm6231t3g1robNBPVOryxDl7glmE7Qf8hlIPupZXQUdEQvYso52HUyD06bpmaLlxHvIzls64rT59oZ78SDoLYDiKgH2uQSek1zLscNw2+nHyF71jvGnCU19+YXZdjZVDYeiknJkR8pybLyQCSbdWDKNFkJzKVNldCHKHTQp3WybtvDr79h8xeGu9xCU75pM/rf+yhwl/MSgR268JFudMDn6u8L/jFs/UJR+Qw+KC4U+WX07GSUPrI4sWe3Rh5SictgYwn/1wjD5gBcWzHCLgdgyiAQMTw50WxVhYxyiJmNRgWibk41JfHl0jMJRJ/hUQSLpEEJAI0Ioa/Qjlu02qe5ko3dFzFB8zaYu4eXShb3a+lWzKa/H2dFcGM0Bps3AomyLvt2AcVusb+rYX1rxBbTsNinUHxFH5aBlIKjyo4wIs2NuQmdqq2+WK5fZ8mCS1oHlEypdUtpTk2wvHmCv5gbKBxaRujr3f6K4QJ3nW9ezqDlWeL5ZslYctHFadEseB5CH9hX3yy3/Soeyu2dK6rND3By59VrQdIALJ/8eYKokNfxUyODk/r5MT4M6f/0UD4+uVhE/TYAbX2OTb7bEB41Ua4Dt9noHvVpu90HX2nn0PfqzZ9p+vwfQa6izZ9W+vo2+qgb6W8U/Gp06LwpePKMauk4YzwCt3YDf6i5pEiGVQdl/NwQTNaltk95KIMbzDxV0Q4Na+q5eE+/igs+oCPQpOM3Y4ittj/WEO2jRf2+8+fP//7t9+O9+fsdlix4YxWwzm9i+vFcsiSYTgUVUhd0CG+GRVGCgsCXOGZ8suXL/fDOJbvovmVkcqueEEN1WU6yyHPVMKDWPf8uj2zu4zwlJzB3QFiFg+x9smbulrWFbHzcDgffk08snL45tNK1bLZ5u8UfA5vynLA+1PB8JdihIKs7sn0HmoPCB/YwEDmEXWzJQBcOs0lQPJjnVXpEpIGlpDxPyDFDvOS5PSWHynxMCaJj7L/OTLX6IB5G2Ca91aA9D/YaYtZvlMJLsiLy7Pzc04Okvc7LZhEO5JAPOsSvwKzGl+m7SW7XngM7ea9kTFiF4QqxBaKg2/uCOq0m/4D8AW75ZCgKeJ+SREqnjXgG2I4VKjnqLxcMp3Vg8kdoFxGomWiEL6AEATKXVC8y8K1WPxIIWhUfJcs1Ei5SDkm7FrdTUASkNLLkVMYeW7ftHCFFAeAFr0z2pFcudeWjWUcmWngyXl9kHtkzJG9P9hxFC2MCQPpYiUtlAFoFVfNwAkYMiiOZqtEbuSTYY3YPlirl6mqtlTUmmo/FJ/QGzyEJM2hGBTCm6b8YNfpxYbCYYGRuQawfwYV2V3w8Gy+6ozna9o8m3OdBY+ciwkeZu6Yiv0wzF6rqrnFpNnw+6LCbCkLsyUWZsAw4PuzPrxndbD1DQ/4Fvn5mOTqs/Exgq93YvhayEJ9s9oBLK/SvKa2bpoXLsjTkR4DYHPppkUCK6VEcH7vpCEYcYPD3wZA3sk/9n9MS1FIh5qd7XhEXjP2ATJFfDyL3MaQZYoLRecKSIeV/mJ8KCWct+cmfG4i5vhkkmR1OYd6HKq16vEy0QBIc36pQrzd5m/WVNxjyxBiqv0csPn41/pp1+b3vwIVNz35Y4YFi+uM/wADD0v/3HoRpnnrXoDfKVwLQmT/1lwiOE3xVe//Mbes2g==""",
    "clar_print_default.c": r"""eJyFVO9r2zAQ/Wz/FbeAiR1ip4R+ctjG6MgYmDHoBoN2BNU6JwJHMpKcdYz+79UPZ5VDk35y7und3dPdUxYzuP3++Ve+Zi3eiO6vZNud/oGPuoTl1fIavgixbRGq6gZmi3gxsCtWI1eYf6XINWsYyhI+daTeYb4sriwzjpUmmtVwEIxC3RK56STjesM406n5ARqV3tSi53oONlY903gEasGVhnpHJMz8ASd7VFn8L45SWzJ7SV/FkSvdpJNKEIoUEuqrqRISdc8nc7Ads1GHsGpQ4VYTqZGaJIM+nb2F2vWaij/87ZtYAKUU0gPnbuChIPM/FiSv4heh99xrjJwqiZ2QeuO4Kr0o3XGcbt7vj5NWWva19jRHgJn7OLnHlmAGm8GasLaXWLq5mhJZqCpRZZkoSBOVwZ0JEvob7nJtPpYeR5Grmn9wFw1iOwsbTrgAiqqWrNNMjFIa49AgbBk36+v3DyhP6gzoSBccjTDw/FD3autYrIF0OAiaw7v38O1nVWWm/Lk6AT0bb+eyfwS3StPQ5l668aP3THATDzRm7khP/WMTVmPE5QSWTmqj12fDR5iup1DCtJi+oc9tKH39HYY2Z5zio1Nl/hy4EJ19/SM7O8aJxb3sS/3JgzH0qL/Z1hyKonDNDmTTMnNE5LZbuVDZl5vaeA5+sdGhGWagNDULc/jcpWQ+BzlNh/ApfgaG5q3r""",
    "clar_print_tap.c": r"""eJyNVN9r2zAQfrb/iotDwDax02Z7SthG17ExCKOwDvYwCKolO2KOZCQlayn933eS7VZO0mVP9n367u67H9Ishe83n35mn3nNrmXzoHi1Mbfs3ixgfjF/C1+krGoGq9U1pLNw1rFXvGBCs+wrZcLwkjO1gKuGFBuWzfMLywxDbYjhBewlp1DURK0bxYVZc8FNjD9gmDbrQu6EmYK19Y4b1gOFFNpAsSEK0vZAkC3TSfgYBrENmby4L3vIIx5gPc9JKOPo9uoG9kxpLgVcvvklomQZPr0qWW92hso/4rxsCzClpGqB/5E7xDznZRgGvIR4NAgYPNcwhoZozSiQuoYJdcJinWAxU08kFhawWrOBY0lw2tQ6ka0U1aG3l3CKfsEwWh/mMs8n9Djb6210YV0PxW7bj1gbtStMS3MESN3Hax2ybS/6vABZlrUj8zCcuSYVgwVM9EsR2fu2lq2uhnTNcPzcPCxcL46iudEAHEVz+JBqi4cTVIsPmSU2/RTT4kNmzUXPpD7T4mtsxx1TSb8e3RFlulC8MXajR+/g24/Vyl8WAI9wKMA7SoadzvP83OWQwq2Of2HdPthr2F6I1nSqW6BdPzfhPtVE2yXMOmEovFvRDxAJaUD+jrAZEX7smR/w2cR0YeDkO3GKNVJ1O6fjMxW4scan3xz/lnNB2f1A9xjSNEXVEI8nNLGGa6zv7rv+Wwa5Q8kDGbi3UzsEl3NP1jXHI6KqZulMjIQO1p5Ct+Jlp0zji7XDFyn6iI0E/B2B2/H9IcGlsCGSNiYTNO7Mp/AvU9H+lQ==""",
    "clar_sandbox.c": r"""eJydVf1v0zAQ/Tn5K45OWpP1K5QJBGVIiH2oomzVWrRJUFlZ4jTWEqey3UFB+985x0mbZOVDTJOa5s5377275w6OYDY9ve2ds4R+yFYbwZaxmtPv6g0MveExXGTZMqEwmXyAo4E9KLInLKBc0t44pFyxiFHxBt6v/CCmvWHf05n2AeNBsg4pvJUqTNhdP35n21L5igUQxL4AEiS+ICtfxV+OvdcvF6NtmHFlM0ke/ISFRKWrPMkJMi6VOXqkX7j2T9uazd/PyRykwtMWi8DRJRwd7sKhVC48OwHPtS1LULUWHLwy79mMjGen42s80JeKpFlI3WZe8ez4QUClLKrekKuPLpzosiP7sYY5YryKN0d6t44iKrog2Q9KFCSULw30AxbxkEZAbsaXL4a2VUqTsyyyH1CgIFtzBSdwPGrkmPqUP6BQQn5ZYA4KYrXmn6bIq9UF/ZR/nJnPz7Oz6+n11fl4ctaywXpEimAVnZjmG2UCHIZ1vBEweLtrP4JOh7l5+UZvTF5ShQ/OFghboDCWERlfalH1KcX4muoueeTpeHWqaYE0BQ9WG6fUDkPdUjldujIky3q08d+2cDPHEaiY6mwmMp7iZkKYUcnbqKe/AZ9vVMz4sgtKbEBlsJYUBthfr+tvQLV0vFXgasIywRqyCjAEdUATSU3pC4qmSldTXdQ5vbm6PnXNsS6Yco3lO6A8ZJHhNY+ZBLmRiqZbQgm7p0igxkWTD9ZC5MSZoIHKMPgHcv3fMuv/iVb5tfe8aoCHjIWQW3rNpc/Du+y7o9/lNtUAKn73FtpA7a9ee8d6pK+MqOqIIEYWiBJhVgSJJBFppZhxoVnI9D5EkVaF9fRj4ivq1m4W1JslISkgGiW2OCvbrQNE+SzJndXK+2npbvO/lnbj1tLlpVK/AHYYjf2zqArbRYNVbyatpm1hMeyG88CHOsmmOj8BV4NnIsWh/qA5XL0I06vZ+BbQyd98EYJMfBlTmS9BxerWE6trEjuTN+fFinl9zedlWY0QtAftrRW3g2rU0Mx68Hyhb2TMN43q8U5nV0zvWbmWuyzoaKTd3XD2KYttMKmQDFAzxmnoEPJpfHlx82JIiFuAS+/zbakeRZqXnyeTJ3PR+bhduI/VqXqvPO/JT4w+gM6vts5HVu9K5F/3Y0/d/wFSXkGlOf5OdzvCne9rP3TG5v9ucjg83Oe6/Q7QVYzzq0D3alGD9wt+Lq2Y""",
    "clar_fixtures.c": r"""eJyFUl1rwjAUfTa/4g4fbG2dTmQwxQdxcxv4IM6BIBJiequBmpQ0Dt3Yf18/rLZuuLfcnHPPOfcmzTq8TR7njZEIcKjCgxbrjZnh3nSh3Wp34FmpdYAwHg+h3iTNI3ssOMoIG68eSiN8gboLg5DxDTbat62ESSLDjODAlYwM8A3TUCe+2JudRhoys7GKyIpF6Ja4OVWyLdrki1RyvQRNBRad1sP9shcj4hOpAa2UoQHKHiGV/Ax9iIyOD1biYCdkoyUPD1Yq4UJmnCgoP7uz7URA+JCVi5NUA+6WcNOHWrNmk0qljDrOElIoby7mX7Ri8NRYRBwn4ZcygXOaxL1gJ3Upapwp56apNcZcma2nR74JqQrfQx+G48GUjl7ns/fpE50MZi+kuGoe0KOLdfUFjuqlR/yl7EKpL03xoYQHZxcaMemt1P66mx9RHv9Hq5CuxHGB8oDpbBF/2vAAmdyF/9rorVWa6ax7MUxqU0XpCZ/8AFmeEnw=""",
    "clar_mock.c": r"""eJy1Vm1r20gQ/lz9iolLEztIsZM2ba/BgdKSI+DLHfSOO+gVs5FG9mJpV6zWdtIj//1mZyVLseViOC4QYs888/7MbIan8OW3z39FNzLDT7p4NHI2t7/jg/0AF6OLN/Cz1rMMYTL5BKfDYFihJzJGVWJ0m6CyMpVoPsDHQsRzjC7ORg4Z2McCE0yhtGYZW/hFx4uJLO2dThD+CaBTfqoo8NU+ZWFw5ZSxVqWFeC4MnKZLFTvZUiqbi4ephZXIlsg+SvkdSRDrpSKnT8+8XQVBaYWV8fMY5TSnr9OMvk/nKBIYc67H2/KwQ0S4uz8mkxBGIUTnYfBEMZq04kyYKZv02/n7z66KEDrkNJRaXlWTSYWDwCW11TkuCmA4hD9FtgA7R3C5wb2IF2thkjKEVBu4ub35Fe5xLlZSmzMycMK+s6Zat2s645YDa4/GuzVXqjH/ia4desANA5Cp9xpdu+JgPObm1FoeopXKTwrgCTArkY1o9HFetGxDbs/AuRg19vcGxaIyDvwvdw6N0Waal7Ov5xfvvzEPVGFoDGl/owq5mbolGYTQu9OQa4PgSvQsKkGshMzEPS2Aa9PJq/LkqFflw0zMpqIs0dhpf2+PwiYlsgle0IC+iBXygDjK2S59Nx3dkHkrUnTNrHYBiW09RwU/Ci+WJUhFtjLpDSpS3KYckUGyVCcWCjS5ULS/IWR6jQakLb09MjEaI4PlMmOv39HoENbkBzEBq0mVay6GlE3jnHlDAJ/TNYzg+BiiqC1sz7ThUHTt7sCmCfVRgNZ3D3zGPA9JDSLH5cIdLQzapVH1XXgKgpWWSbWPa5llUw/472sZVtTc+fHIrRlvHLTP1L7NpkJjkWU67p9vyNtGDbbpyEt3NK4uUo80rVJhLe28ZghXaaVWoESOni/txYX6xLYYSdINM5+Nsz62nj4fE+bIPc6kUlLNQKd8k4L2JLvOTj3xZrjQdX3ccneZVrSomH8jH5aFJ7/TEeHNY81vxfJYlI7CwjZXcy1KwLywj5R96q4CM9zNIPQfXTshFwv0njovJxSaZu5a4KOvOS3an7mM526d1i4mbdNaKHvWteWccTNG3nPOL9bGLAuLyVF7YjubwXyvHrqG9pwqLTXavhM60r3Y18iOru9i909oF1uxylXUpa75NepS1iyLzn9QWJyhUMtiU1rXPoXNvxo/fP8YdMj7R7jNHeu+XbuHaXsWAy7KPeBzYgyWdI4db9wnsqblXGuzOApe0mUdBY5YM3raW2VWy00kYqfuH7A+wbxbh8+FVE4Cwsy2DhtJVl+/eT/Pj0XfRQnh8t1rTrx6S3scmx5leJX8rehN9N8HV24ZCLvPzfnF6/pU7SrfXL7dr3z3/qeDE6AoByIp5IFIir+T2pQJWSf49jKEw5tE8P8FeQC04crIceMlqkSmwb+bENvx""",
    "clar_fs.c": r"""eJydVW1v2kgQ/mz/ihGVGjuBQGnuS0lPigjuoSMQgaP0miDXtdewOttr7S4JaS///WZfMJBSReoXYJ6dfWZ2npmhfQyz68vPrYDmpM+qJ04XSxmStfwA3U73DD4xtsgJjEZ9OG67bes9ogkpBWkNU1JKmlHCP8BFFSdL0uqedpSn+4ZmKckguh2O33fRRIOWBIJJEAWji08z8NTP2XA0GIfwn8bHk/5kHAynVxfhcDKuwcF0OpneDF86Xf19OZz6ritkLGkCyTLmcOxm+A5WiaiK5dJLWCmkPdGI7/5wHWMrEz7C+GY06rmOoN9JJCEn5UIum0B7ruvQDLzIuBk/33UcTuSKl/aa65gLyCMkx9/G30dCS1/Eec4Sz7qdQNffML9CXJAiqZ60VxMi82VYNux3xpxjlM4+hHHeWdh1MsbBo9oCCueWpAcnJ9QHrEadzB2dq3yO2kcqHaeG4Oj+/ggDPCOZTVKd9dznuvYPjKabynu0lFCwlDRhr/yCrXjyEkyJkFqT2V8BdsLkehZOb/ohZEikkjdu5ipmsieuZVTlMG6K7CcnHUFRfSGcXZGC8SfvraJvgtKcZd5+aN83RavE6WOwKhOlIT6mZ7Eq4KxQcuvYNRoyxFSoDZIFebwQCNb9rp+TR7EQhMvIwxJjYEx1UhGORWSlSctXGnSaeNy4pWXKHgW88IMsRjNtuI5JlRPibUuhTfvolwKJiBfeAVG0Ahv5gkl0ORgNwgG23UYz3aOH+BLcGIcYfyXzTpD+5PqfnRDRNmdNjqVS/DmJy1XlKcgQ6DdkdI19SKzESR5zOyGN44ZvSN6QXJA6X+xJVyxJnkdsJT2TlU0x5ouHu7kmV52rLqyEmiea4kLAT1Vk/FKdxfi/3naAETuHjhmirOJ4O/OETAnnSj6nMXsSkhSANsP1+NXc/goJrgSr4el92VCiOWRNpdd659sx29CrVjD8ZE2SB0/n2pk3ddIb58eYSnRWF5rw1uTfxHu9elxvB5+H4Sy8CG9mnjm3NaJlkq9SAue4vWi5OF3++ZsK1wIbU+f5x7y3P8DbNWvsCFeRKmY93phFimLvDPbWcbti61NTJ2Pe7Xi29ParN9mvHMx6tCVFs9H+Rst2UjV6FtVOjda0Brrz3cnX0HsF2Yby7QLQB2fz+s9Fz32xEhKbVAg9+tte1ErqcQ90S4BkoGoOUm0z2+hCoSIu029sfXjuXx31nUnf0ehsfqgGvPipBtl+ETYvPlCM332zmXSQS7L/0lcWgh7+VWmvePrfQEE7wDMugzKlmfs/5DzCtQ==""",
    "clar_categorize.c": r"""eJydVW1v2jAQ/pz8iitTUV6A0mqfyqiE6IsqRdvUtdKmrorcYIqlNGG2mcqq/fedz4EamtBtXyCx787P89xzzkEEXz6ffu2ei5yPy/lSioeZvuZP+hiO+kfv4aIsH3IOSTKG6MA/qKITkfFC8e7lhBdaTAWXxzCas2zGu0e9von03034VBQcxsnoKh2Prs8uPl19S0/Pzkc3yTW0cJctct3yfb2cc3wDpeUi0/Dse1lZKA3ZjEmIooI9cjXwPVHgUrkodPXM8rzMBv5vyHIm04xp/lDKZZoLhRG+0kyLrGYPUndN/OIpL9h9zicvSXTSRqIoKDeoKReZ3w64kDEg9J8tSoFop6WEQMAQ+gMQ8AFMRvfEcoE4FqHveWIKAQqQMcWzx3mAJTpVHPG/FXchDLGCifUk1wtZwCHWrh77KMQa/89STLYIsMkk1eV/kUBg9WJUORhnQFkgKCJlOBThZFgxoY6FpsGeswDxEA4R/2qR+KJYktN24Kx23EIQgcL2ldPAhR2GWAmlcIvdOmji+A5rI+g3BLOmCLYUoT2SpVnedpPBSCtb4a8OT5FmYCimGtRCaJ4Sg1WbqnGhTNqGiP4U4avyjP02pomYb8OvyNZOamjCtx3swMGFODYGoBgsiVEWB3q2t1IBJ9iwh3abdKQXm1YPheznqvR6JmlMiBopGLGVMPb1nmSoxqMLzmyxzv1bDZhLPG/Vtw0TzCXeak/uePveD1VKHTS1vVdZt3HfdhWlqLNz5zXr2o7srr6+ZojYNGjtq331vWh1wPLZgW59/ezuhlDWhFuiNZnUzpBrTJWx9e2xt5uNIfKPBqaqdDLeA2tPvtxbDfe98eeOeX5jYAyl1TS4xw6A2MLeED7eJMkAzJudhubbdgcMqhZufRk2Pw1/ANHTpwM=""",
    "clar.h": r"""eJxljjsLwjAUhff8ikt1KrSV4tRN6hM6iHZwC6U5bS/URJIIivjfTcFBcD3nO48spvNxfUm2PKI0t6flfvA1Hr6gfJEvaWdMP4KqqqQ4E9mXrriFdkgOCtpzx7AFrW5NOyDJ08VEihl3WqEjKctqdZL15lzLvZRiFkTW+NNDQLfjXYGidmysbJyD9S4dIhFmY0Ex1XCervCDUaQwUY1no52YBuevcBpWy1/nHWqhFXfiA5YySSw=""",
}
if __name__ == "__main__":
    main()
